### ISSUE TITLE
Multiple calls to setWindowSize hang Firefox

### ISSUE THREAD

**Issue by GARMBoshouwers** [theintern/leadfoot#115]
When calling setWindowSize to set a size to which the browser has been set before, Firefox (or Selenium?) hangs. This does not happen when it is called with different sizes.

Intern: 3.4.4
Firefox: 54.0.1
geckodriver: 1.8.0 (32 bit)

This code fails:
```
return this.remote
	.setWindowSize(1920, 1080)
	.setWindowSize(1920, 1080)
;
```

This code seems to work fine:

```
return this.remote
	.setWindowSize(1920, 1080)
	.setWindowSize(192, 108)
	.setWindowSize(1920, 1080)
;
```

**Comment by jason0x43** [comment]
This appears to be a Firefox issue, at least as of FF 53 and geckodriver 0.16.0 (and apparently still in FF 54 and gd 0.18), and we haven't had a chance to build a workaround into Leadfoot. It sounds like the issue may be fixed in FF 55 (https://github.com/mozilla/geckodriver/issues/703#issuecomment-298562800).

**Comment by GARMBoshouwers** [comment]
I checked this in Firefox 55.0.2 with the same Intern and GeckoDriver versions. It works correctly now.

**Comment by jason0x43** [comment]
Great, thanks for the update!
