### ISSUE TITLE
ECONNREFUSED error is unhelpful

### ISSUE THREAD

**Issue by csnover** [theintern/leadfoot#12]
This problem is due to upstream Dojo 2 core library passing errors as-is from the underlying Node.js request client instead of making the errors minimally friendly and useful.

**Comment by juanpicado** [comment]
I'm having this issue with Intern 2.2.2 and I think is the issue is related with the ticket #22 , Browserstack boots the device well but in some point, Leadfoot crash in this point, the response object is undefined and is not able to execute response.getHeader. My environment is using Android or iPhone capabilities, it doesn't happen with normal browsers. It could be related with this ticket?
``````
************************************************
response response--> { [Error: [GET /wd/hub/session/5f8d81c1183fdef9ce892b4de27d6a047cef5200] connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
************************************************
response TYPEOF--> undefined
************************************************
response TYPEOF--> undefined
FATAL ERROR
TypeError: undefined is not a function
  at handleResponse  <node_modules/intern/node_modules/leadfoot/Server.js:81:32>
``````
