### ISSUE TITLE
Synchronous commands via `execSync`

### ISSUE THREAD

**Issue by jugglinmike** [theintern/leadfoot#35]
In https://github.com/theintern/intern/issues/101, there was some discussion about exposing a synchronous API via the `wd-sync` library. One of the main objections to this was that project's need to compile native add-ons.

I'm also interested in authoring integration tests with a synchronous API, so I'd like to raise the feature request with a different implementation approach.

Node 0.12 introduces `process.execSync`--this could be used to wrap each request to the Selenium server. I think that if implemented at a low enough level, there would not need to be much additional logic.

I can see two drawbacks to this approach:

1. Speed (a new process must be spawned for each command)
2. Compatibility (`process.execSync` is only available in the latest version of Node.js)

`#1` could be addressed with a "caveat emptor". `#2` could also be addressed through documentation (i.e. "Note: Leadfoot's synchronous API is only available for Node.js >= 0.12"). I'd be willing to help out with the implementation work, but I wanted to get input from the maintainers first. Is this in scope for the project?

**Comment by vladikoff** [comment]
@jugglinmike I use https://www.npmjs.com/package/sync-exec that has no native add-ons and it also uses 0.12's execSync: https://github.com/gvarsanyi/sync-exec/blob/master/coffee/sync-exec.coffee#L93

**Comment by jugglinmike** [comment]
@vladikoff Oh, that's a neat project! Thanks for the tip! I guess that means `#2` could be a non-issue. At the same time, I imagine that performance would suffer when using the shimmed code path, so `#1` might be a bigger caveat for Node 0.10 users.

**Comment by csnover** [comment]
TypeScript 1.6 plans to include [async/await](https://github.com/Microsoft/TypeScript/issues/1664) following the [ES7 strawman](http://wiki.ecmascript.org/doku.php?id=strawman:async_functions), which use Promise objects and generators as backing mechanisms for managing asynchronicity, so if you were to write a test using TS 1.6 it would just look like this:

```js
async function myTest() {
  await session.get('https://www.example.com');
  var fooElement = await session.findById('foo');
  await fooElement.click();
  var barElement = await session.findById('bar');
  // ...
}
```

Since the compiler emits ES5 code this function would be consumable by Intern today with no changes.

Also, as mentioned, this is part of a ES7 proposal and the keywords are reserved in ES6 for this purpose, so other transpilers will also start to support this same syntax and there should be no need for any other work.

You can also use a coroutine runner with generators today to do basically the same thing:

```js
function myTest() {
  return async.run(function* () {
    yield session.get('https://www.example.com');
    var fooElement = yield session.findById('foo');
    yield fooElement.click();
    var barElement = yield session.findById('bar');
    // ...
  });
}
```

So, I don’t feel like there is a good reason to invoke anything like execSync to try to do this, the proper solution for native procedural async is coming in the language itself plus various supporting tools within the year.

**Comment by jugglinmike** [comment]
Thanks for the thoughtful reply, @csnover! Unfortunately, I don't think I can use either of the alternatives you've suggested:

- async/await - I personally don't feel comfortable maintaining code written
  against a straw man proposal. Obviously opinions on this vary, and I can
  appreciate that some application developers may choose to take that risk.
  That said, it seems like a bit of a dodge for a library to make design
  decisions based on a proposed future language extension.
- generators - I *think* these are available in Io.js, but the above
  reservations about platform stability/support prevent me from using that
  project in any professional work.

Both approaches also require additional syntax to model fundamentally synchronous work. User interactions occur in series, and the browser receives them as such. From this perspective, *any* abstraction (whether callbacks, promises, async/await, or coroutine runners) is unfortunate overhead both in terms of characters in the source and required cognition when reading, writing and teaching.

I'll admit: using `execSync` to achieve this is far from elegant. That said, it will work today on a stable platform, and it won't effect consumers who don't care to use it.

**Comment by csnover** [comment]
> async/await - I personally don't feel comfortable maintaining code written against a straw man proposal. Obviously opinions on this vary, and I can appreciate that some application developers may choose to take that risk. That said, it seems like a bit of a dodge for a library to make design decisions based on a proposed future language extension.

Nothing is a sure thing, but this is pretty close. The keywords are reserved, the process is… in process, implementations are appearing soon, and the semantics of async/await are simple, well known, and well defined—basically a transplant from C# where they exist and have been used successfully for years.

> generators - I think these are available in Io.js, but the above reservations about platform stability/support prevent me from using that project in any professional work.

Generators are available since Node.js 0.11.2 with `--harmony` flag.

> Both approaches also require additional syntax to model fundamentally synchronous work.

Well, this is why the chained interface exists, to abstract and reduce the impact of the asynchronous nature of the underlying implementation. Unfortunately, blocking the main loop just does a lot of bad stuff:

* Intern’s instrumenting proxy won’t be able to serve responses
* Intern’s tests won’t be able to execute in parallel
* etc.

In order to prevent these things you will have to add a lot of overhead, IPCs, and general complexity in the system when you could just write a DSL instead and compile it.

**Comment by jugglinmike** [comment]
> Unfortunately, blocking the main loop just does a lot of bad stuff:
>
> - Intern’s instrumenting proxy won’t be able to serve responses
> - Intern’s tests won’t be able to execute in parallel
> - etc.
>
> In order to prevent these things you will have to add a lot of overhead,
> IPCs, and general complexity in the system when you could just write a DSL
> instead and compile it.

Those tasks could be completed with a blocking API by using multiple processes. To be sure, this would require more code/infrastructure in the examples you've described. At the same time, those tasks reflect a significantly more advanced use case, and they are also only indirectly related to the problem of expressing integration tests.

I think we can both agree that there is a certain amount of unavoidable burden to modeling asynchronous communication. We just disgree about where this belongs. I think it makes more sense to optimize the API for writing tests and moving the burden to the more advanced use cases you've identified. (Memory space isolation would be an additional benefit of embracing this independence in the process architecture.)

...but I don't think you would have built such an extensive tool without having already considered these issues. This is more likely a difference in philosophies, so I may be barking up the wrong tree. (I'll keep my eyes peeled for [docs on custom interfaces in Intern](https://theintern.github.io/intern/#custom-interfaces).) Just know that I really appreciate the work that you're doing here; this aspect of the API is just a fly in the ointment for me.

**Comment by csnover** [comment]
> (I'll keep my eyes peeled for docs on custom interfaces in Intern.) 

If you want you can look at any of the existing interfaces (in lib/interfaces) to understand how they work, luckily they’re not really complicated, they just instantiate Suite and Test objects and register them with the test system. To make one that understands a DSL, you just:

1. Decide what you want your DSL to look like (JavaScript? More human readable? Up to you!)
2. Write a parser to convert a file written in that DSL to an actual set of suites/tests
3. Write tests using your DSL and register them using your custom interface, which if you implement the interface as a loader plugin would be as simple as putting this in your Intern config:

```js
functionalSuites: [ 'my/custom/dsl!my/functional/testfile.customdsl' ]
```

Once Intern 3 is finalised I hope to be able to fill in those remaining sections to describe what the interfaces need to do more specifically.

**Comment by jugglinmike** [comment]
Roger roger. Thanks!

**Comment by csnover** [comment]
@jugglinmike The [custom interfaces section](https://theintern.github.io/intern/#custom-interfaces) has some words in it now that should hopefully let you know how to do this. Let me know about unclear stuff by opening documentation tickets on the Intern repo. Thanks!
