### ISSUE TITLE
Electron: 'dynamicViewport' and 'takesScreenshot' detection hangs the runner for 20 seconds

### ISSUE THREAD

**Issue by vladikoff** [theintern/leadfoot#41]
The following feature detection hangs the test runner for ~20 seconds during startup when running in the Electron environment:
```
if (!('dynamicViewport' in capabilities)) {
  testedCapabilities.dynamicViewport = session.getWindowSize().then(function (originalSize) {
    return session.setWindowSize(originalSize.width, originalSize.height);
  }).then(supported, unsupported);
}
```
Ref: https://github.com/theintern/leadfoot/blob/master/Server.js#L460

```
// At least Selendroid 0.9.0 will fail to take screenshots in certain device configurations, usually
// emulators with hardware acceleration enabled
testedCapabilities.takesScreenshot = session.takeScreenshot().then(supported, unsupported);
```
Ref: https://github.com/theintern/leadfoot/blob/master/Server.js#L443

If I remove the 2 checks above then the tests proceed swiftly.

To reproduce see: https://github.com/vladikoff/intern-examples/tree/i3/electron-example

**Comment by csnover** [comment]
You can pass `fixSessionCapabilities: false` in current versions of Leadfoot to bypass all of the detections. Otherwise, hangs on those commands should be reported to upstream to be fixed, since there isn’t anything that the client can really do if the server is just slow/hanging. #48 could be implemented to reduce this problem.

**Comment by csnover** [comment]
Closing since there is nothing to be done in this specific case except to implement enhancement #48.
