### ISSUE TITLE
File with extension .shtml is downloaded by browser instead of displayed

### ISSUE THREAD

**Issue by cwaldren** [theintern/leadfoot#43]
Most of my html files have the .shtml extension because they utilize server-side-includes. When the test runner fires up Chrome, Chrome directly downloads the file instead of loading it properly. Perhaps it is being treated like an external file instead of as the page source?

My functional test includes this
````
    .get(require.toUrl("whatever.shtml))
````

I'm not sure if this is by-design or not.

ChromeDriver: `2.16`
OS: `Windows 7`
Selenium: `2.46`
Intern-geezer: `2.2.2`

**Comment by csnover** [comment]
Server-side includes need to be supported on the server you are using for them to…work. In this case, the Intern proxy doesn’t do SSI so the content is returned as application/octet-stream since the extension is unknown. If you want to use SSI you will need to follow the [Testing non-CORS APIs](https://theintern.github.io/intern/#testing-cors) and point to a different HTTP server with SSI support. Future versions of Intern will include improvements for adding middleware to the proxy but this will be covered under another ticket in the Intern repository. As such I am closing this ticket for now. Thanks!

**Comment by cwaldren** [comment]
Yes, that makes total sense. I neglected to say that I am only using SSI for including CSS, and so I don't care if it actually executes. To clarify, I was wondering if the files could be treated as .html without me having to make two copies with both extensions.
