### ISSUE TITLE
Is there any command similar to 'waitForElementVisible

### ISSUE THREAD

**Issue by mbhatti03** [theintern/leadfoot#45]
Is there any command similar to 'waitForElementVisible' or 'waitForPageLoad()' as we have in selenium webdriver? It seems for now we either have to use sleep or setTimeout.

**Comment by jason0x43** [comment]
Thanks for writing! In order to keep the bug tracker focused on development, we ask that people not submit questions here. Please see the [Getting Support](https://theintern.github.io/intern/#getting-help) page for information on where to submit questions.

That said, Intern 3 (currently in beta) includes a set of `findDisplayedByX` methods to find visible elements. In both Intern 3 and Intern 2 you can use `pollUntil` or a standard `findBy` command to wait for a page load.
