### ISSUE TITLE
Array<Element> Loop 

### ISSUE THREAD

**Issue by brunano21** [theintern/leadfoot#50]
Hi,

using .findAllByCssSelector('.css-selector') I get an <Element> array. I would like to search for an  element which has a particular `VisibleText` and if found I would like to get that element, not its text. 

Any suggestion?

**Comment by csnover** [comment]
Thanks for writing! In order to keep the bug tracker focused only on the development of Intern itself, we ask that people please follow the [contribution guidelines](https://github.com/theintern/leadfoot/blob/master/CONTRIBUTING.md) and not submit questions to the bug tracker. This is a perfect Q&A question for [Stack Overflow](http://stackoverflow.com/questions/ask?tags=intern), so please submit there so other people with the same question can find it. Thank you!
