### ISSUE TITLE
execute/executeAsync commands don't seem to be working.

### ISSUE THREAD

**Issue by stsvilik** [theintern/leadfoot#80]
What I want to test is a global property that should be created by a script on my test page, but neither **execute** nor **executeAsync** works.

What I did was the following:
```js
//inside a bdd.it block
this.remote
        .get(require.toUrl('index.html'))
        .execute(function() {
            return window.foo; //foo being a property which my script sets (it is there when tested by itself);
         })
         .then(function(fooValue) {
              //fooValue is always null
         });
```

Same story for execute async.

I also tried running same test with **webdriverio** and was able to successfully extract foo value demonstrated above.

**Comment by jason0x43** [comment]
It's hard to tell without seeing `index.html`, but the problem is likely that `foo` is being created by Javascript code that's running asynchronously. The `get` call resolves just after the static page loading process is complete (when a `load` even would typically fire). At this point, no async scripts have run. You could add a [`sleep`](https://theintern.github.io/leadfoot/module-leadfoot_Command.html#sleep) command after the `get` to give the page time to run any initial scripts, but a better solution is to use [`pollUntil`](https://theintern.github.io/leadfoot/module-leadfoot_helpers_pollUntil.html) to wait for some condition to exist that definitively shows that the page has finished initializing.

**Comment by stsvilik** [comment]
I will try sleep however even when I try to return something native like **location** I still get undefined.

**Comment by jason0x43** [comment]
That would definitely be a problem; returning `window.location` from an execute block should work fine (and it does in my own testing).

What browser are you using?

**Comment by stsvilik** [comment]
local Selenium + Chrome

**Comment by jason0x43** [comment]
Does this simple test case work? https://gist.github.com/jason0x43/b961c24aaf19ab4351f5bb559eae2bb6

**Comment by vladikoff** [comment]
Here is another example https://github.com/mozilla/fxa-content-server/blob/883fdbefaee1b666cf2893a6dc315a192ac1489c/tests/functional/settings_devices.js#L111

**Comment by stsvilik** [comment]
I'll try it again. Does BDD interface work with these tests as well, because thats what I'm using?

**Comment by jason0x43** [comment]
Yes. Leadfoot commands are independent of the interface being used.

Also, make sure you're returning the result of the `this.remote` call (e.g., `return this.remote.get(...)...`). Otherwise, Intern will assume the test is synchronous and won't wait for the browser actions to complete.

**Comment by stsvilik** [comment]
All good guys, thanx for the help

**Comment by aamster** [comment]
I'm having a similar problem, except I'm using **executeAsync**. I expect the return value to be passed to the callback to executeAsync, but this is not happening. Should the following work?

```javascript
return this.remote.get(require.toUrl(url))
    .findByCssSelector
    ...
    .executeAsync(function() {
        return ...
    .then(function() {
        ...
    }.then(function() {
        return [item1, item2];
    }
    }).then(function(items) {
        console.log("ITEMS", items); // items is undefined
    }
```

Execution gets to the last callback in executeAsync successfully. The callback to executeAsync is called successfully. But the value passed to the executeAsync callback is `undefined`.
