### ISSUE TITLE
IE11 secretly using synthetic mouse events

### ISSUE THREAD

**Issue by wkeese** [theintern/leadfoot#83]
I specified my environment as:

```
{ browserName: "internet explorer", version: "11", platform: "Windows 8.1", requireWindowFocus: "true"}
```

Correspondingly, when I run the test, I can see from `console.log()` that `environmentType.nativeEvents` is `true`.

Yet behind the scenes, Intern (or WebDriver?) is using synthetic events, as seen from the call to `simulateMouse()` in the SauceLabs log:

```
POST execute
44.82s (+0.06s)
args: [{"action":"mousedown","position":{"y":51,"x":190.5999908447266},"button":0}]
script: "return (function simulateMouse(kwArgs) {\n\tvar position = kwArgs.position;\n\n\tfunction dispatch(kwArgs) {\n\t\tvar event = document.createEvent('MouseEvents');\n\t\tevent.initMouseEvent(\n\t\t\tkwArgs.type,\n\t\t\tkwArgs.bubbles || true,\n\t\t\tkwArgs.cancelable || false,\n\t\t\twindow,\n\t\t\tkwArgs.detail || 0,\n\t\t\twindow.screenX + position.x,\n\t\t\twindow.screenY + position.y,\n\t\t\tposition.x,\n\t\t\tposition.y,\n\t\t\tkwArgs.ctrlKey || false,\n\t\t\tkwArgs.altKey || false,\n\t\t\tkwArgs.shiftKey || false,...
```

That makes me hit a problem similar to #17: `.pressMouseButton(0)` generates a `MouseEvent` but not a `PointerEvent`.  (Perhaps that should be a separate ticket.)

**Comment by jason0x43** [comment]
Check for the `brokenMouseEvents` capability. It detects inconsistent firing of mouse events, and if it's true, mouse events will be simulated. In the past that flag was only applied to Safari. however, in some recent updates I noticed that the mouse event self tests were frequently failing in IE10 an 11 due to mouse events being fired inconsistently, so I added a feature test.

Currently you can set `environmentType.brokenMouseEvents` to false in your tests if you want, or disable feature testing. Ideally, you should be able to pre-define feature flag values to avoid them being tested.

**Comment by wkeese** [comment]
Indeed, `remote.environmentType.brokenMouseEvents = true`.   I tried setting `remote.environmentType.brokenMouseEvents = false` at the beginning of the test but it still calls `simulateMouse`.  (But even if I was able to disable the synthetic mouse events, I might hit the webdriver problem you mentioned about "mouse events being fired inconsistently".

So I think the Leadfoot problem is more accurately described by #17 and #103 (which I just filed), so I'll close this ticket.
